### ISSUE TITLE
여성의 경우에만 성별 표기하는 기사 찾기

### ISSUE THREAD

**Issue by kkyueing** [itpas2020/newsmon#3]
`analyze.py`의 `analyze_gender()` 함수를 구현하고 `analyze_test.py`에 단위 테스트를 추가해야 합니다.

**Comment by fl-ada** [comment]
여성을 특정할 수 있는 [키워드](https://github.com/itpas2020/newsmon/blob/master/README.md#%EC%97%AC%EC%84%B1%ED%8A%B9%EC%A0%95-%ED%91%9C%ED%98%84) 추가했습니다.

**Comment by akngs** [comment]
여기로 옮겨 적을게요 :)

* (00세, 여/女)
* 엄마 / 모정 / 母 / 친모 / 親母 / 어머니
* 딸
* 아내 / 부인
* 여자친구/ 여친
* 여00 / 女00. 예) 여교사, 여중생, 여교사 등
* 00녀/女. 예) 동거녀, 미녀, (범죄특성)녀, n0대녀, 00대(학)녀 등. 제외) 자녀, 남(주로 특수문자로 분리되어 사용되고 붙은 경우도 있음)녀

**Comment by kkyueing** [comment]
여기에도 복붙할게요:

* (00세, 여/女)
* 엄마 / 모정 / 母 / 친모 / 親母 / 어머니
* 딸
* 아내 / 부인
* 여자친구/ 여친
* 여00 / 女00. 예) 여교사, 여중생, 여교사 등
* 00녀/女. 예) 동거녀, 미녀, (범죄특성)녀, n0대녀, 00대(학)녀 등. 제외) 자녀, 남(주로 특수문자로 분리되어 사용되고 붙은 경우도 있음)녀
