### ISSUE TITLE
성범죄를 미화/축소하는 표현 기사 찾기

### ISSUE THREAD

**Issue by fl-ada** [itpas2020/newsmon#6]
성범죄 관련 기사에 한하여, 아래 키워드 검사하기.

* 곤욕
* 검은 손 / 검은손
* 손찌검
* 홧김에
* 비정한
* 일탈
* 충동
* 우발
* 순간의 실수 / 한순간 실수 등
* 어린 나이 / 철 없

**Comment by kkyueing** [comment]
이걸 하려면 해당 기사가 성범죄 관련 기사인지 여부를 판단하는 로직이 필요하겠어요. 그걸 먼저 만들어볼게요.

**Comment by fl-ada** [comment]
네 다른 키워드 중에도 사건사고 기사를 분류하는 로직이 필요한 것이 있습니다.
이 경우에도 가정폭력 등에서도 사용되는 표현이라 성범죄보단 사건사고/범죄 기사가 맞을 것 같습니다.

**Comment by kkyueing** [comment]
네 그렇게 만들어볼게요 :)

**Comment by fl-ada** [comment]
README에 나쁜 손 등 몇가지 추가됐습니다.

**Comment by kkyueing** [comment]
사건/사고 일반으로 확대하면 [파파라치 학원 '몰카'](https://news.v.daum.net/v/20200326060049214) 기사를 걸러낼 수가 없을 것 같아요. 사이트 취지에 맞게 성범죄/성차별에 대한 기사만 추려내면 좋을 것 같아요. 일단은 그렇게 좁혀서 만들어볼게요!

**Comment by kkyueing** [comment]
각 주제(몰카, 미투, 리벤지포르노 등) 별로 우선 특정 패턴에 일치하는지를 기준으로 후보를 고르고, 그 중에서 '예외 패턴'에 일치하는 기사는 제외시키는 식으로 만들었어요. 예를 들어 '몰카'의 경우, 우선 '몰카'나 '몰래카메라'가 나오는 기사를 추려내고, 이 중에서 '파파라치 학원' 관련된 기사는 빼는 식으로요.
